/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as MlLabRouteImport } from './routes/ml-lab'
import { Route as CameraRouteImport } from './routes/camera'
import { Route as ProjectsRouteRouteImport } from './routes/projects/route'
import { Route as PRouteRouteImport } from './routes/p/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as PProjectIdRouteImport } from './routes/p/$projectId'
import { Route as ProjectsProjectIdRouteRouteImport } from './routes/projects/$projectId/route'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdTrainRouteImport } from './routes/projects/$projectId/train'
import { Route as ProjectsProjectIdPlayRouteImport } from './routes/projects/$projectId/play'
import { Route as ProjectsProjectIdLabelIndexRouteImport } from './routes/projects/$projectId/label/index'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const MlLabRoute = MlLabRouteImport.update({
  id: '/ml-lab',
  path: '/ml-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraRoute = CameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRouteRoute = ProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PRouteRoute = PRouteRouteImport.update({
  id: '/p',
  path: '/p',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const PProjectIdRoute = PProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => PRouteRoute,
} as any)
const ProjectsProjectIdRouteRoute = ProjectsProjectIdRouteRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRouteRoute,
} as any)
const ProjectsProjectIdTrainRoute = ProjectsProjectIdTrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => ProjectsProjectIdRouteRoute,
} as any)
const ProjectsProjectIdPlayRoute = ProjectsProjectIdPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => ProjectsProjectIdRouteRoute,
} as any)
const ProjectsProjectIdLabelIndexRoute =
  ProjectsProjectIdLabelIndexRouteImport.update({
    id: '/label/',
    path: '/label/',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p': typeof PRouteRouteWithChildren
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/camera': typeof CameraRoute
  '/ml-lab': typeof MlLabRoute
  '/todos': typeof TodosRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteRouteWithChildren
  '/p/$projectId': typeof PProjectIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/play': typeof ProjectsProjectIdPlayRoute
  '/projects/$projectId/train': typeof ProjectsProjectIdTrainRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/label/': typeof ProjectsProjectIdLabelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/p': typeof PRouteRouteWithChildren
  '/camera': typeof CameraRoute
  '/ml-lab': typeof MlLabRoute
  '/todos': typeof TodosRoute
  '/p/$projectId': typeof PProjectIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/play': typeof ProjectsProjectIdPlayRoute
  '/projects/$projectId/train': typeof ProjectsProjectIdTrainRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/label': typeof ProjectsProjectIdLabelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/p': typeof PRouteRouteWithChildren
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/camera': typeof CameraRoute
  '/ml-lab': typeof MlLabRoute
  '/todos': typeof TodosRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteRouteWithChildren
  '/p/$projectId': typeof PProjectIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/play': typeof ProjectsProjectIdPlayRoute
  '/projects/$projectId/train': typeof ProjectsProjectIdTrainRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/label/': typeof ProjectsProjectIdLabelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/p'
    | '/projects'
    | '/camera'
    | '/ml-lab'
    | '/todos'
    | '/projects/$projectId'
    | '/p/$projectId'
    | '/projects/'
    | '/projects/$projectId/play'
    | '/projects/$projectId/train'
    | '/projects/$projectId/'
    | '/projects/$projectId/label/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/p'
    | '/camera'
    | '/ml-lab'
    | '/todos'
    | '/p/$projectId'
    | '/projects'
    | '/projects/$projectId/play'
    | '/projects/$projectId/train'
    | '/projects/$projectId'
    | '/projects/$projectId/label'
  id:
    | '__root__'
    | '/'
    | '/p'
    | '/projects'
    | '/camera'
    | '/ml-lab'
    | '/todos'
    | '/projects/$projectId'
    | '/p/$projectId'
    | '/projects/'
    | '/projects/$projectId/play'
    | '/projects/$projectId/train'
    | '/projects/$projectId/'
    | '/projects/$projectId/label/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PRouteRoute: typeof PRouteRouteWithChildren
  ProjectsRouteRoute: typeof ProjectsRouteRouteWithChildren
  CameraRoute: typeof CameraRoute
  MlLabRoute: typeof MlLabRoute
  TodosRoute: typeof TodosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ml-lab': {
      id: '/ml-lab'
      path: '/ml-lab'
      fullPath: '/ml-lab'
      preLoaderRoute: typeof MlLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera': {
      id: '/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof CameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p': {
      id: '/p'
      path: '/p'
      fullPath: '/p'
      preLoaderRoute: typeof PRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/p/$projectId': {
      id: '/p/$projectId'
      path: '/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof PProjectIdRouteImport
      parentRoute: typeof PRouteRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/train': {
      id: '/projects/$projectId/train'
      path: '/train'
      fullPath: '/projects/$projectId/train'
      preLoaderRoute: typeof ProjectsProjectIdTrainRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/play': {
      id: '/projects/$projectId/play'
      path: '/play'
      fullPath: '/projects/$projectId/play'
      preLoaderRoute: typeof ProjectsProjectIdPlayRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/label/': {
      id: '/projects/$projectId/label/'
      path: '/label'
      fullPath: '/projects/$projectId/label/'
      preLoaderRoute: typeof ProjectsProjectIdLabelIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
  }
}

interface PRouteRouteChildren {
  PProjectIdRoute: typeof PProjectIdRoute
}

const PRouteRouteChildren: PRouteRouteChildren = {
  PProjectIdRoute: PProjectIdRoute,
}

const PRouteRouteWithChildren =
  PRouteRoute._addFileChildren(PRouteRouteChildren)

interface ProjectsProjectIdRouteRouteChildren {
  ProjectsProjectIdPlayRoute: typeof ProjectsProjectIdPlayRoute
  ProjectsProjectIdTrainRoute: typeof ProjectsProjectIdTrainRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdLabelIndexRoute: typeof ProjectsProjectIdLabelIndexRoute
}

const ProjectsProjectIdRouteRouteChildren: ProjectsProjectIdRouteRouteChildren =
  {
    ProjectsProjectIdPlayRoute: ProjectsProjectIdPlayRoute,
    ProjectsProjectIdTrainRoute: ProjectsProjectIdTrainRoute,
    ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
    ProjectsProjectIdLabelIndexRoute: ProjectsProjectIdLabelIndexRoute,
  }

const ProjectsProjectIdRouteRouteWithChildren =
  ProjectsProjectIdRouteRoute._addFileChildren(
    ProjectsProjectIdRouteRouteChildren,
  )

interface ProjectsRouteRouteChildren {
  ProjectsProjectIdRouteRoute: typeof ProjectsProjectIdRouteRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteRouteChildren: ProjectsRouteRouteChildren = {
  ProjectsProjectIdRouteRoute: ProjectsProjectIdRouteRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteRouteWithChildren = ProjectsRouteRoute._addFileChildren(
  ProjectsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PRouteRoute: PRouteRouteWithChildren,
  ProjectsRouteRoute: ProjectsRouteRouteWithChildren,
  CameraRoute: CameraRoute,
  MlLabRoute: MlLabRoute,
  TodosRoute: TodosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
